import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type AttackSeed = { name: string; attackBonus: string; damage: string };

type BeastSeed = {
  id: string; name: string; nameEn: string; cr: number; crLabel: string;
  ac: number; hp: number; hitDice: string;
  speedWalk: number; speedFly: number; speedSwim: number; speedClimb: number; speedBurrow: number;
  size: string; strength: number; dexterity: number; constitution: number;
  attacks: AttackSeed[]; traits: string;
  vulnerabilities: string | null; resistances: string | null; immunities: string | null; conditionImmunities: string | null;
  multiattack: boolean; minDruidLevel: number | null; minMoonDruidLevel: number | null; source: string;
};

const BEASTS: BeastSeed[] = [
  { id: "beast-spider", name: "Araña", nameEn: "Spider", cr: 0.0, crLabel: "0", ac: 12, hp: 1, hitDice: "1d4-1",
    speedWalk: 20, speedFly: 0, speedSwim: 0, speedClimb: 20, speedBurrow: 0,
    size: "Diminuto", strength: 2, dexterity: 14, constitution: 8,
    attacks: [{ name: "Mordisco", attackBonus: "+4", damage: "1 perforante (alcance 5 pies) [DC 9 CON, 1d4 P, NA]" }],
    traits: "Spider Climb, Web Sense, Web Walker", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.337" },
  { id: "beast-vulture", name: "Buitre", nameEn: "Vulture", cr: 0.0, crLabel: "0", ac: 10, hp: 5, hitDice: "1d8+1",
    speedWalk: 10, speedFly: 50, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 7, dexterity: 10, constitution: 13,
    attacks: [{ name: "Pico", attackBonus: "+2", damage: "1d4 perforante (alcance 5 pies)" }],
    traits: "Pack Tactics", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.339" },
  { id: "beast-owl", name: "Búho", nameEn: "Owl", cr: 0.0, crLabel: "0", ac: 11, hp: 1, hitDice: "1d4-1",
    speedWalk: 5, speedFly: 60, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Diminuto", strength: 3, dexterity: 13, constitution: 8,
    attacks: [{ name: "Garras", attackBonus: "+3", damage: "1 cortante (alcance 5 pies)" }],
    traits: "Flyby", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.333" },
  { id: "beast-sea-horse", name: "Caballito de mar", nameEn: "Sea Horse", cr: 0.0, crLabel: "0", ac: 11, hp: 1, hitDice: "1d4-1",
    speedWalk: 0, speedFly: 0, speedSwim: 20, speedClimb: 0, speedBurrow: 0,
    size: "Diminuto", strength: 1, dexterity: 12, constitution: 8,
    attacks: [],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 4, source: "MM p.337" },
  { id: "beast-goat", name: "Cabra", nameEn: "Goat", cr: 0.0, crLabel: "0", ac: 10, hp: 4, hitDice: "1d8",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 12, dexterity: 10, constitution: 11,
    attacks: [{ name: "Embestida", attackBonus: "+3", damage: "1d4+1 contundente (alcance 5 pies)" }],
    traits: "Charge, Sure Footed", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.330" },
  { id: "beast-crab", name: "Cangrejo", nameEn: "Crab", cr: 0.0, crLabel: "0", ac: 11, hp: 2, hitDice: "1d4",
    speedWalk: 20, speedFly: 0, speedSwim: 20, speedClimb: 0, speedBurrow: 0,
    size: "Diminuto", strength: 2, dexterity: 11, constitution: 10,
    attacks: [{ name: "Garra", attackBonus: "+0", damage: "1 contundente (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 4, source: "MM p.320" },
  { id: "beast-jackal", name: "Chacal", nameEn: "Jackal", cr: 0.0, crLabel: "0", ac: 12, hp: 3, hitDice: "1d6",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Pequeño", strength: 8, dexterity: 15, constitution: 11,
    attacks: [{ name: "Mordisco", attackBonus: "+1", damage: "1d4-1 perforante (alcance 5 pies)" }],
    traits: "Pack Tactics", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.331" },
  { id: "beast-deer", name: "Ciervo", nameEn: "Deer", cr: 0.0, crLabel: "0", ac: 13, hp: 4, hitDice: "1d8",
    speedWalk: 50, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 11, dexterity: 16, constitution: 11,
    attacks: [{ name: "Mordisco", attackBonus: "+2", damage: "1d4 perforante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.321" },
  { id: "beast-weasel", name: "Comadreja", nameEn: "Weasel", cr: 0.0, crLabel: "0", ac: 13, hp: 1, hitDice: "1d4-1",
    speedWalk: 30, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Diminuto", strength: 3, dexterity: 16, constitution: 8,
    attacks: [{ name: "Mordisco", attackBonus: "+5", damage: "1 perforante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.340" },
  { id: "beast-raven", name: "Cuervo", nameEn: "Raven", cr: 0.0, crLabel: "0", ac: 12, hp: 1, hitDice: "1d4-1",
    speedWalk: 10, speedFly: 50, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Diminuto", strength: 2, dexterity: 14, constitution: 8,
    attacks: [{ name: "Pico", attackBonus: "+4", damage: "1 perforante (alcance 5 pies)" }],
    traits: "Mimicry", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.335" },
  { id: "beast-giant-fire-beetle", name: "Escarabajo de fuego gigante", nameEn: "Giant Fire Beetle", cr: 0.0, crLabel: "0", ac: 13, hp: 4, hitDice: "1d6+1",
    speedWalk: 30, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Pequeño", strength: 8, dexterity: 10, constitution: 12,
    attacks: [{ name: "Mordisco", attackBonus: "+1", damage: "1d6-1 cortante (alcance 5 pies)" }],
    traits: "Illumination", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.325" },
  { id: "beast-scorpion", name: "Escorpión", nameEn: "Scorpion", cr: 0.0, crLabel: "0", ac: 11, hp: 1, hitDice: "1d4-1",
    speedWalk: 10, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Diminuto", strength: 2, dexterity: 11, constitution: 8,
    attacks: [{ name: "Aguijón", attackBonus: "+2", damage: "1 perforante (alcance 5 pies) [DC 9 CON, 1d8 P | Half, NA]" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.337" },
  { id: "beast-cat", name: "Gato", nameEn: "Cat", cr: 0.0, crLabel: "0", ac: 12, hp: 2, hitDice: "1d4",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 30, speedBurrow: 0,
    size: "Diminuto", strength: 3, dexterity: 15, constitution: 10,
    attacks: [{ name: "Garras", attackBonus: "+0", damage: "1 cortante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.320" },
  { id: "beast-hawk", name: "Halcón", nameEn: "Hawk", cr: 0.0, crLabel: "0", ac: 13, hp: 1, hitDice: "1d4-1",
    speedWalk: 10, speedFly: 60, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Diminuto", strength: 5, dexterity: 16, constitution: 8,
    attacks: [{ name: "Garras", attackBonus: "+5", damage: "1 cortante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.330" },
  { id: "beast-hyena", name: "Hiena", nameEn: "Hyena", cr: 0.0, crLabel: "0", ac: 11, hp: 5, hitDice: "1d8+1",
    speedWalk: 50, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 11, dexterity: 13, constitution: 12,
    attacks: [{ name: "Mordisco", attackBonus: "+2", damage: "1d6 perforante (alcance 5 pies)" }],
    traits: "Pack Tactics", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.331" },
  { id: "beast-lizard", name: "Lagarto", nameEn: "Lizard", cr: 0.0, crLabel: "0", ac: 10, hp: 2, hitDice: "1d4",
    speedWalk: 20, speedFly: 0, speedSwim: 0, speedClimb: 20, speedBurrow: 0,
    size: "Diminuto", strength: 2, dexterity: 11, constitution: 10,
    attacks: [{ name: "Mordisco", attackBonus: "+0", damage: "1 perforante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.332" },
  { id: "beast-baboon", name: "Mandril", nameEn: "Baboon", cr: 0.0, crLabel: "0", ac: 12, hp: 3, hitDice: "1d6",
    speedWalk: 30, speedFly: 0, speedSwim: 0, speedClimb: 30, speedBurrow: 0,
    size: "Pequeño", strength: 8, dexterity: 14, constitution: 11,
    attacks: [{ name: "Mordisco", attackBonus: "+1", damage: "1d4-1 perforante (alcance 5 pies)" }],
    traits: "Pack Tactics", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.318" },
  { id: "beast-bat", name: "Murciélago", nameEn: "Bat", cr: 0.0, crLabel: "0", ac: 12, hp: 1, hitDice: "1d4-1",
    speedWalk: 5, speedFly: 30, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Diminuto", strength: 2, dexterity: 15, constitution: 8,
    attacks: [{ name: "Mordisco", attackBonus: "+2", damage: "1 perforante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.318" },
  { id: "beast-octopus", name: "Pulpo", nameEn: "Octopus", cr: 0.0, crLabel: "0", ac: 12, hp: 3, hitDice: "1d6",
    speedWalk: 5, speedFly: 0, speedSwim: 30, speedClimb: 0, speedBurrow: 0,
    size: "Pequeño", strength: 4, dexterity: 15, constitution: 11,
    attacks: [{ name: "Tentáculos", attackBonus: "+4", damage: "1 contundente (alcance 5 pies) [NA, G, DC 10]" }],
    traits: "Ink Cloud", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 4, source: "MM p.333" },
  { id: "beast-quipper", name: "Quipper", nameEn: "Quipper", cr: 0.0, crLabel: "0", ac: 13, hp: 1, hitDice: "1d4-1",
    speedWalk: 0, speedFly: 0, speedSwim: 40, speedClimb: 0, speedBurrow: 0,
    size: "Diminuto", strength: 2, dexterity: 16, constitution: 9,
    attacks: [{ name: "Mordisco", attackBonus: "+5", damage: "1 perforante (alcance 5 pies)" }],
    traits: "Blood Frenzy", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 4, source: "MM p.335" },
  { id: "beast-frog", name: "Rana", nameEn: "Frog", cr: 0.0, crLabel: "0", ac: 11, hp: 1, hitDice: "1d4-1",
    speedWalk: 0, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Diminuto", strength: 1, dexterity: 13, constitution: 8,
    attacks: [],
    traits: "Standing Leap", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 4, source: "MM p.322" },
  { id: "beast-rat", name: "Rata", nameEn: "Rat", cr: 0.0, crLabel: "0", ac: 10, hp: 1, hitDice: "1d4-1",
    speedWalk: 20, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Diminuto", strength: 2, dexterity: 11, constitution: 9,
    attacks: [{ name: "Mordisco", attackBonus: "+0", damage: "1 perforante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.335" },
  { id: "beast-badger", name: "Tejón", nameEn: "Badger", cr: 0.0, crLabel: "0", ac: 10, hp: 3, hitDice: "1d4+1",
    speedWalk: 20, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 5,
    size: "Diminuto", strength: 4, dexterity: 11, constitution: 12,
    attacks: [{ name: "Mordisco", attackBonus: "+2", damage: "1 perforante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.318" },
  { id: "beast-eagle", name: "Águila", nameEn: "Eagle", cr: 0.0, crLabel: "0", ac: 12, hp: 3, hitDice: "1d6",
    speedWalk: 10, speedFly: 60, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Pequeño", strength: 6, dexterity: 15, constitution: 10,
    attacks: [{ name: "Garras", attackBonus: "+4", damage: "1d4+2 cortante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.322" },
  { id: "beast-camel", name: "Camello", nameEn: "Camel", cr: 0.125, crLabel: "1/8", ac: 9, hp: 15, hitDice: "2d10+4",
    speedWalk: 50, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 16, dexterity: 8, constitution: 14,
    attacks: [{ name: "Mordisco", attackBonus: "+5", damage: "1d4 contundente (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.320" },
  { id: "beast-giant-crab", name: "Cangrejo gigante", nameEn: "Giant Crab", cr: 0.125, crLabel: "1/8", ac: 15, hp: 13, hitDice: "3d8",
    speedWalk: 30, speedFly: 0, speedSwim: 30, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 13, dexterity: 15, constitution: 11,
    attacks: [{ name: "Garra", attackBonus: "+3", damage: "1d6+1 contundente (alcance 5 pies) [NA, G, DC 11]" }],
    traits: "Each Claw Can Grapple", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 4, source: "MM p.324" },
  { id: "beast-giant-weasel", name: "Comadreja gigante", nameEn: "Giant Weasel", cr: 0.125, crLabel: "1/8", ac: 13, hp: 9, hitDice: "2d8",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 11, dexterity: 16, constitution: 10,
    attacks: [{ name: "Mordisco", attackBonus: "+5", damage: "1d4+3 perforante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.329" },
  { id: "beast-stirge", name: "Estirge", nameEn: "Stirge", cr: 0.125, crLabel: "1/8", ac: 14, hp: 2, hitDice: "1d4",
    speedWalk: 10, speedFly: 40, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Diminuto", strength: 4, dexterity: 16, constitution: 11,
    attacks: [{ name: "Drenaje de sangre", attackBonus: "+5", damage: "1d4+3 perforante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.284" },
  { id: "beast-blood-hawk", name: "Halcón sanguinario", nameEn: "Blood Hawk", cr: 0.125, crLabel: "1/8", ac: 12, hp: 7, hitDice: "2d6",
    speedWalk: 10, speedFly: 60, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Pequeño", strength: 6, dexterity: 14, constitution: 10,
    attacks: [{ name: "Pico", attackBonus: "+4", damage: "1d4+2 perforante (alcance 5 pies)" }],
    traits: "Pack Tactics", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.319" },
  { id: "beast-mastiff", name: "Mastín", nameEn: "Mastiff", cr: 0.125, crLabel: "1/8", ac: 12, hp: 5, hitDice: "1d8+1",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 13, dexterity: 14, constitution: 12,
    attacks: [{ name: "Mordisco", attackBonus: "+3", damage: "1d6+1 perforante (alcance 5 pies) [DC 11 STR, PR, NA]" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.332" },
  { id: "beast-mule", name: "Mula", nameEn: "Mule", cr: 0.125, crLabel: "1/8", ac: 10, hp: 11, hitDice: "2d8+2",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Medium*", strength: 14, dexterity: 10, constitution: 13,
    attacks: [{ name: "Cascos", attackBonus: "+2", damage: "1d4+2 contundente (alcance 5 pies)" }],
    traits: "Sure Footed, Beast of Burden", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.333" },
  { id: "beast-pony", name: "Poni", nameEn: "Pony", cr: 0.125, crLabel: "1/8", ac: 10, hp: 11, hitDice: "2d8+2",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 15, dexterity: 10, constitution: 13,
    attacks: [{ name: "Cascos", attackBonus: "+4", damage: "2d4+2 contundente (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.335" },
  { id: "beast-giant-rat", name: "Rata gigante", nameEn: "Giant Rat", cr: 0.125, crLabel: "1/8", ac: 12, hp: 7, hitDice: "2d6",
    speedWalk: 30, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Pequeño", strength: 7, dexterity: 15, constitution: 11,
    attacks: [{ name: "Mordisco", attackBonus: "+4", damage: "1d4+2 perforante (alcance 5 pies)" }],
    traits: "Pack Tactics", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.327" },
  { id: "beast-diseased-giant-rat", name: "Rata gigante enferma †", nameEn: "Diseased Giant Rat †", cr: 0.125, crLabel: "1/8", ac: 12, hp: 7, hitDice: "2d6",
    speedWalk: 30, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Pequeño", strength: 7, dexterity: 15, constitution: 11,
    attacks: [{ name: "Mordisco", attackBonus: "+3", damage: "1d4+1 perforante (alcance 5 pies) [DC 10 CON, Diseased, NA]" }],
    traits: "Pack Tactics", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.327" },
  { id: "beast-poisonous-snake", name: "Serpiente venenosa", nameEn: "Poisonous Snake", cr: 0.125, crLabel: "1/8", ac: 13, hp: 2, hitDice: "1d4",
    speedWalk: 30, speedFly: 0, speedSwim: 30, speedClimb: 0, speedBurrow: 0,
    size: "Diminuto", strength: 2, dexterity: 16, constitution: 11,
    attacks: [{ name: "Mordisco", attackBonus: "+5", damage: "1 perforante (alcance 5 pies) [DC 10 CON, 2d4 PS | Half, NA]" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 4, source: "MM p.334" },
  { id: "beast-flying-snake", name: "Serpiente voladora", nameEn: "Flying Snake", cr: 0.125, crLabel: "1/8", ac: 14, hp: 5, hitDice: "2d4",
    speedWalk: 30, speedFly: 60, speedSwim: 30, speedClimb: 0, speedBurrow: 0,
    size: "Diminuto", strength: 4, dexterity: 18, constitution: 11,
    attacks: [{ name: "Mordisco", attackBonus: "+6", damage: "1 perforante + 3d4 veneno (alcance 5 pies)" }],
    traits: "Flyby", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.322" },
  { id: "beast-elk", name: "Alce", nameEn: "Elk", cr: 0.25, crLabel: "1/4", ac: 10, hp: 13, hitDice: "2d10+2",
    speedWalk: 50, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 16, dexterity: 10, constitution: 12,
    attacks: [{ name: "Embestida", attackBonus: "+5", damage: "1d6+3 contundente (alcance 5 pies)" }, { name: "Cascos", attackBonus: "+5", damage: "M [PR], 2d4+3 contundente (alcance 5 pies)" }],
    traits: "Charge", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.322" },
  { id: "beast-giant-wolf-spider", name: "Araña lobo gigante", nameEn: "Giant Wolf Spider", cr: 0.25, crLabel: "1/4", ac: 13, hp: 11, hitDice: "2d8+2",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 40, speedBurrow: 0,
    size: "Mediano", strength: 12, dexterity: 16, constitution: 13,
    attacks: [{ name: "Mordisco", attackBonus: "+3", damage: "1d6+1 perforante (alcance 5 pies) [DC 11 CON, 2d6 PS | Half, NA]" }],
    traits: "Spider Climb, Web Sense, Web Walker", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.330" },
  { id: "beast-giant-owl", name: "Búho gigante", nameEn: "Giant Owl", cr: 0.25, crLabel: "1/4", ac: 12, hp: 19, hitDice: "3d10+3",
    speedWalk: 5, speedFly: 60, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 13, dexterity: 15, constitution: 12,
    attacks: [{ name: "Garras", attackBonus: "+3", damage: "2d6+1 cortante (alcance 5 pies)" }],
    traits: "Flyby", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.327" },
  { id: "beast-riding-horse", name: "Caballo de monta", nameEn: "Riding Horse", cr: 0.25, crLabel: "1/4", ac: 10, hp: 13, hitDice: "2d10+2",
    speedWalk: 60, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 16, dexterity: 10, constitution: 12,
    attacks: [{ name: "Cascos", attackBonus: "+5", damage: "2d4+3 contundente (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.336" },
  { id: "beast-draft-horse", name: "Caballo de tiro", nameEn: "Draft Horse", cr: 0.25, crLabel: "1/4", ac: 10, hp: 19, hitDice: "3d10+3",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 18, dexterity: 10, constitution: 12,
    attacks: [{ name: "Cascos", attackBonus: "+6", damage: "2d4+4 contundente (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.321" },
  { id: "beast-giant-centipede", name: "Ciempiés gigante", nameEn: "Giant Centipede", cr: 0.25, crLabel: "1/4", ac: 13, hp: 4, hitDice: "1d6+1",
    speedWalk: 30, speedFly: 0, speedSwim: 0, speedClimb: 30, speedBurrow: 0,
    size: "Pequeño", strength: 5, dexterity: 14, constitution: 12,
    attacks: [{ name: "Mordisco", attackBonus: "+4", damage: "1d4+2 perforante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.323" },
  { id: "beast-boar", name: "Jabalí", nameEn: "Boar", cr: 0.25, crLabel: "1/4", ac: 11, hp: 11, hitDice: "2d8+2",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 13, dexterity: 11, constitution: 12,
    attacks: [{ name: "Colmillo", attackBonus: "+3", damage: "1d6+1 cortante (alcance 5 pies)" }],
    traits: "Charge, Relentless", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.319" },
  { id: "beast-giant-lizard", name: "Lagarto gigante", nameEn: "Giant Lizard", cr: 0.25, crLabel: "1/4", ac: 12, hp: 19, hitDice: "3d10+3",
    speedWalk: 30, speedFly: 0, speedSwim: 0, speedClimb: 30, speedBurrow: 0,
    size: "Grande", strength: 15, dexterity: 12, constitution: 13,
    attacks: [{ name: "Mordisco", attackBonus: "+4", damage: "1d8+2 perforante (alcance 5 pies)" }],
    traits: "Spider Climb †, Mount", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.326" },
  { id: "beast-giant-lizard-variant", name: "Lagarto gigante (variante) †", nameEn: "Giant Lizard Variant †", cr: 0.25, crLabel: "1/4", ac: 12, hp: 19, hitDice: "3d10+3",
    speedWalk: 30, speedFly: 0, speedSwim: 30, speedClimb: 30, speedBurrow: 0,
    size: "Grande", strength: 15, dexterity: 12, constitution: 13,
    attacks: [{ name: "Mordisco", attackBonus: "+4", damage: "1d8+2 perforante (alcance 5 pies)" }],
    traits: "Spider Climb †, Mount", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 4, source: "MM p.326" },
  { id: "beast-wolf", name: "Lobo", nameEn: "Wolf", cr: 0.25, crLabel: "1/4", ac: 13, hp: 11, hitDice: "2d8+2",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 12, dexterity: 15, constitution: 12,
    attacks: [{ name: "Mordisco", attackBonus: "+4", damage: "2d4+2 perforante (alcance 5 pies) [DC 11 STR, PR, NA]" }],
    traits: "Pack Tactics", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.341" },
  { id: "beast-giant-bat", name: "Murciélago gigante", nameEn: "Giant Bat", cr: 0.25, crLabel: "1/4", ac: 13, hp: 22, hitDice: "4d10",
    speedWalk: 10, speedFly: 60, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 15, dexterity: 16, constitution: 11,
    attacks: [{ name: "Mordisco", attackBonus: "+4", damage: "1d6+2 perforante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.323" },
  { id: "beast-panther", name: "Pantera", nameEn: "Panther", cr: 0.25, crLabel: "1/4", ac: 12, hp: 13, hitDice: "3d8",
    speedWalk: 50, speedFly: 0, speedSwim: 0, speedClimb: 40, speedBurrow: 0,
    size: "Mediano", strength: 14, dexterity: 15, constitution: 10,
    attacks: [{ name: "Mordisco", attackBonus: "+4", damage: "1d6+2 perforante (alcance 5 pies)" }, { name: "Garras", attackBonus: "+4", damage: "1d4+2 cortante (alcance 5 pies)" }],
    traits: "Pounce", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.333" },
  { id: "beast-axe-beak", name: "Pico de hacha", nameEn: "Axe Beak", cr: 0.25, crLabel: "1/4", ac: 11, hp: 19, hitDice: "3d10+3",
    speedWalk: 50, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 14, dexterity: 12, constitution: 12,
    attacks: [{ name: "Pico", attackBonus: "+4", damage: "1d8+2 cortante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.317" },
  { id: "beast-pteranodon", name: "Pteranodon", nameEn: "Pteranodon", cr: 0.25, crLabel: "1/4", ac: 13, hp: 13, hitDice: "3d8",
    speedWalk: 10, speedFly: 60, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 12, dexterity: 15, constitution: 10,
    attacks: [{ name: "Mordisco", attackBonus: "+3", damage: "2d4+1 perforante (alcance 5 pies)" }],
    traits: "Flyby", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.80" },
  { id: "beast-giant-frog", name: "Rana gigante", nameEn: "Giant Frog", cr: 0.25, crLabel: "1/4", ac: 11, hp: 18, hitDice: "4d8",
    speedWalk: 30, speedFly: 0, speedSwim: 30, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 12, dexterity: 13, constitution: 11,
    attacks: [{ name: "Mordisco", attackBonus: "+3", damage: "1d6+1 perforante (alcance 5 pies) [NA, G/RS, DC 11]" }],
    traits: "Swallow, Standing Leap", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 4, source: "MM p.325" },
  { id: "beast-constrictor-snake", name: "Serpiente constrictora", nameEn: "Constrictor Snake", cr: 0.25, crLabel: "1/4", ac: 12, hp: 13, hitDice: "2d10+2",
    speedWalk: 30, speedFly: 0, speedSwim: 30, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 15, dexterity: 14, constitution: 12,
    attacks: [{ name: "Mordisco", attackBonus: "+4", damage: "1d6+2 perforante (alcance 10 pies)" }, { name: "Constricción", attackBonus: "+4", damage: "1d8+2 contundente (alcance 5 pies) [NA, G/RS, DC 14]" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 4, source: "MM p.320" },
  { id: "beast-giant-poisonous-snake", name: "Serpiente venenosa gigante", nameEn: "Giant Poisonous Snake", cr: 0.25, crLabel: "1/4", ac: 14, hp: 11, hitDice: "2d8+2",
    speedWalk: 30, speedFly: 0, speedSwim: 30, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 10, dexterity: 18, constitution: 13,
    attacks: [{ name: "Mordisco", attackBonus: "+6", damage: "1d4+4 perforante (alcance 10 pies) [DC 11 CON, 3d6 PS | Half, NA]" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 4, source: "MM p.327" },
  { id: "beast-giant-badger", name: "Tejón gigante", nameEn: "Giant Badger", cr: 0.25, crLabel: "1/4", ac: 10, hp: 13, hitDice: "2d10+2",
    speedWalk: 30, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 10,
    size: "Mediano", strength: 13, dexterity: 10, constitution: 15,
    attacks: [{ name: "Mordisco", attackBonus: "+3", damage: "1d6+1 perforante (alcance 5 pies)" }, { name: "Garras", attackBonus: "+3", damage: "2d4+1 cortante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 2, minMoonDruidLevel: 2, source: "MM p.323" },
  { id: "beast-giant-wasp", name: "Avispa gigante", nameEn: "Giant Wasp", cr: 0.5, crLabel: "1/2", ac: 12, hp: 13, hitDice: "3d8",
    speedWalk: 10, speedFly: 50, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 10, dexterity: 14, constitution: 10,
    attacks: [{ name: "Aguijón", attackBonus: "+4", damage: "1d6+2 perforante (alcance 5 pies) [DC 11 CON, 3d6 PS | Half, NA]" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.329" },
  { id: "beast-giant-sea-horse", name: "Caballito de mar gigante", nameEn: "Giant Sea Horse", cr: 0.5, crLabel: "1/2", ac: 13, hp: 16, hitDice: "3d10",
    speedWalk: 0, speedFly: 0, speedSwim: 40, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 12, dexterity: 15, constitution: 11,
    attacks: [{ name: "Embestida", attackBonus: "+3", damage: "1d6+1 contundente (alcance 5 pies)" }],
    traits: "Charge", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 4, source: "MM p.328" },
  { id: "beast-warhorse", name: "Caballo de guerra", nameEn: "Warhorse", cr: 0.5, crLabel: "1/2", ac: 11, hp: 19, hitDice: "3d10+3",
    speedWalk: 60, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 18, dexterity: 12, constitution: 13,
    attacks: [{ name: "Cascos", attackBonus: "+6", damage: "2d6+4 contundente (alcance 5 pies)" }],
    traits: "Trampling Charge", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 2, source: "MM p.340" },
  { id: "beast-giant-goat", name: "Cabra gigante", nameEn: "Giant Goat", cr: 0.5, crLabel: "1/2", ac: 11, hp: 19, hitDice: "3d10+3",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 17, dexterity: 11, constitution: 12,
    attacks: [{ name: "Embestida", attackBonus: "+5", damage: "2d4+3 contundente (alcance 5 pies)" }],
    traits: "Charge, Sure Footed", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 2, source: "MM p.326" },
  { id: "beast-crocodile", name: "Cocodrilo", nameEn: "Crocodile", cr: 0.5, crLabel: "1/2", ac: 12, hp: 19, hitDice: "3d10+3",
    speedWalk: 20, speedFly: 0, speedSwim: 30, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 15, dexterity: 10, constitution: 13,
    attacks: [{ name: "Mordisco", attackBonus: "+4", damage: "1d10+2 perforante (alcance 5 pies) [NA, G/RS, DC 12]" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 4, source: "MM p.320" },
  { id: "beast-black-bear", name: "Oso negro", nameEn: "Black Bear", cr: 0.5, crLabel: "1/2", ac: 11, hp: 19, hitDice: "3d8+6",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 30, speedBurrow: 0,
    size: "Mediano", strength: 15, dexterity: 10, constitution: 14,
    attacks: [{ name: "Mordisco", attackBonus: "+3", damage: "1d6+2 perforante (alcance 5 pies)" }, { name: "Garras", attackBonus: "+3", damage: "2d4+2 cortante (alcance 5 pies)" }],
    traits: "MA (Bite, Claw)", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: true, minDruidLevel: 4, minMoonDruidLevel: 2, source: "MM p.318" },
  { id: "beast-ape", name: "Simio", nameEn: "Ape", cr: 0.5, crLabel: "1/2", ac: 12, hp: 19, hitDice: "3d8+6",
    speedWalk: 30, speedFly: 0, speedSwim: 0, speedClimb: 30, speedBurrow: 0,
    size: "Mediano", strength: 16, dexterity: 14, constitution: 14,
    attacks: [{ name: "Puño", attackBonus: "+5", damage: "1d6+3 contundente (alcance 5 pies)" }, { name: "Roca", attackBonus: "+5", damage: "1d6+3 contundente (alcance 25/50 pies)" }],
    traits: "MA (Two Fist Attacks), Athletics +5", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: true, minDruidLevel: 4, minMoonDruidLevel: 2, source: "MM p.317" },
  { id: "beast-reef-shark", name: "Tiburón de arrecife", nameEn: "Reef Shark", cr: 0.5, crLabel: "1/2", ac: 12, hp: 22, hitDice: "4d8+4",
    speedWalk: 0, speedFly: 0, speedSwim: 40, speedClimb: 0, speedBurrow: 0,
    size: "Mediano", strength: 14, dexterity: 13, constitution: 13,
    attacks: [{ name: "Mordisco", attackBonus: "+4", damage: "1d8+2 perforante (alcance 5 pies)" }],
    traits: "Pack Tactics", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 4, minMoonDruidLevel: 4, source: "MM p.336" },
  { id: "beast-giant-spider", name: "Araña gigante", nameEn: "Giant Spider", cr: 1.0, crLabel: "1", ac: 14, hp: 26, hitDice: "4d10+4",
    speedWalk: 30, speedFly: 0, speedSwim: 0, speedClimb: 30, speedBurrow: 0,
    size: "Grande", strength: 14, dexterity: 16, constitution: 12,
    attacks: [{ name: "Mordisco", attackBonus: "+5", damage: "1d8+3 perforante (alcance 5 pies)" }, { name: "Telaraña", attackBonus: "+5", damage: "(alcance 30/60 pies) [NA, RS, DC 12 STR]" }],
    traits: "Spider Climb, Web Sense, Web Walker", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 2, source: "MM p.328" },
  { id: "beast-giant-vulture", name: "Buitre gigante", nameEn: "Giant Vulture", cr: 1.0, crLabel: "1", ac: 10, hp: 22, hitDice: "3d10+6",
    speedWalk: 10, speedFly: 60, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 15, dexterity: 10, constitution: 15,
    attacks: [{ name: "Pico", attackBonus: "+4", damage: "2d4+2 perforante (alcance 5 pies)" }, { name: "Garras", attackBonus: "+4", damage: "2d6+2 cortante (alcance 5 pies)" }],
    traits: "MA (Beak, Talons), Pack Tactics", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: true, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.329" },
  { id: "beast-giant-hyena", name: "Hiena gigante", nameEn: "Giant Hyena", cr: 1.0, crLabel: "1", ac: 12, hp: 45, hitDice: "6d10+12",
    speedWalk: 50, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 16, dexterity: 14, constitution: 14,
    attacks: [{ name: "Mordisco", attackBonus: "+5", damage: "2d6+3 perforante (alcance 5 pies)" }],
    traits: "Rampage", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 2, source: "MM p.326" },
  { id: "beast-lion", name: "León", nameEn: "Lion", cr: 1.0, crLabel: "1", ac: 12, hp: 26, hitDice: "4d10+4",
    speedWalk: 50, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 17, dexterity: 15, constitution: 13,
    attacks: [{ name: "Mordisco", attackBonus: "+5", damage: "1d8+3 perforante (alcance 5 pies)" }, { name: "Garras", attackBonus: "+5", damage: "1d6+3 cortante (alcance 5 pies)" }],
    traits: "Pack Tactics, Pounce, Running Leap", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 2, source: "MM p.331" },
  { id: "beast-dire-wolf", name: "Lobo terrible", nameEn: "Dire Wolf", cr: 1.0, crLabel: "1", ac: 14, hp: 37, hitDice: "5d10+10",
    speedWalk: 50, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 17, dexterity: 15, constitution: 15,
    attacks: [{ name: "Mordisco", attackBonus: "+5", damage: "2d6+3 perforante (alcance 5 pies) [DC 13 STR, PR, NA]" }],
    traits: "Pack Tactics", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 2, source: "MM p.321" },
  { id: "beast-brown-bear", name: "Oso pardo", nameEn: "Brown Bear", cr: 1.0, crLabel: "1", ac: 11, hp: 34, hitDice: "4d10+12",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 30, speedBurrow: 0,
    size: "Grande", strength: 19, dexterity: 10, constitution: 16,
    attacks: [{ name: "Mordisco", attackBonus: "+5", damage: "1d8+4 perforante (alcance 5 pies)" }, { name: "Garras", attackBonus: "+5", damage: "2d6+4 cortante (alcance 5 pies)" }],
    traits: "MA (Bite, Claws)", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: true, minDruidLevel: 8, minMoonDruidLevel: 2, source: "MM p.319" },
  { id: "beast-giant-octopus", name: "Pulpo gigante", nameEn: "Giant Octopus", cr: 1.0, crLabel: "1", ac: 11, hp: 52, hitDice: "8d10+8",
    speedWalk: 10, speedFly: 0, speedSwim: 60, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 17, dexterity: 13, constitution: 13,
    attacks: [{ name: "Tentáculos", attackBonus: "+5", damage: "2d6+3 contundente (alcance 15 pies) [NA, G/RS, DC 16]" }],
    traits: "Ink Cloud", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 4, source: "MM p.326" },
  { id: "beast-giant-toad", name: "Sapo gigante", nameEn: "Giant Toad", cr: 1.0, crLabel: "1", ac: 11, hp: 39, hitDice: "6d10+6",
    speedWalk: 20, speedFly: 0, speedSwim: 40, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 15, dexterity: 13, constitution: 13,
    attacks: [{ name: "Mordisco", attackBonus: "+4", damage: "1d10+2 perforante + 1d10 veneno (alcance 5 pies) [NA, G/RS, DC 13 STR]" }],
    traits: "Swallow, Standing Leap", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 4, source: "MM p.329" },
  { id: "beast-tiger", name: "Tigre", nameEn: "Tiger", cr: 1.0, crLabel: "1", ac: 12, hp: 37, hitDice: "5d10+10",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 17, dexterity: 15, constitution: 14,
    attacks: [{ name: "Mordisco", attackBonus: "+5", damage: "1d10+3 perforante (alcance 5 pies)" }, { name: "Garras", attackBonus: "+5", damage: "1d8+3 cortante (alcance 5 pies)" }],
    traits: "Pounce", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: 8, minMoonDruidLevel: 2, source: "MM p.339" },
  { id: "beast-giant-eagle", name: "Águila gigante", nameEn: "Giant Eagle", cr: 1.0, crLabel: "1", ac: 13, hp: 26, hitDice: "4d10+4",
    speedWalk: 10, speedFly: 80, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 16, dexterity: 17, constitution: 13,
    attacks: [{ name: "Pico", attackBonus: "+5", damage: "1d6+3 perforante (alcance 5 pies)" }, { name: "Garras", attackBonus: "+5", damage: "2d6+2 cortante (alcance 5 pies)" }],
    traits: "MA (Beak, Talons)", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: true, minDruidLevel: 8, minMoonDruidLevel: 8, source: "MM p.324" },
  { id: "beast-giant-elk", name: "Alce gigante", nameEn: "Giant Elk", cr: 2.0, crLabel: "2", ac: 14, hp: 42, hitDice: "5d12+10",
    speedWalk: 60, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Enorme", strength: 19, dexterity: 16, constitution: 14,
    attacks: [{ name: "Embestida", attackBonus: "+6", damage: "2d6+4 contundente (alcance 10 pies)" }, { name: "Cascos", attackBonus: "+6", damage: "M [PR], 4d8+4 contundente (alcance 5 pies)" }],
    traits: "Charge", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: null, minMoonDruidLevel: 6, source: "MM p.325" },
  { id: "beast-allosaurus", name: "Alosaurio", nameEn: "Allosaurus", cr: 2.0, crLabel: "2", ac: 13, hp: 51, hitDice: "6d10+18",
    speedWalk: 60, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 19, dexterity: 13, constitution: 17,
    attacks: [{ name: "Mordisco", attackBonus: "+6", damage: "2d10+4 perforante (alcance 5 pies)" }, { name: "Garras", attackBonus: "+6", damage: "1d8+4 cortante (alcance 5 pies)" }],
    traits: "Pounce", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: null, minMoonDruidLevel: 6, source: "MM p.79" },
  { id: "beast-giant-boar", name: "Jabalí gigante", nameEn: "Giant Boar", cr: 2.0, crLabel: "2", ac: 12, hp: 42, hitDice: "5d10+15",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 17, dexterity: 10, constitution: 16,
    attacks: [{ name: "Colmillo", attackBonus: "+5", damage: "2d6+3 cortante (alcance 5 pies)" }],
    traits: "Charge, Relentless", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: null, minMoonDruidLevel: 6, source: "MM p.323" },
  { id: "beast-cave-bear", name: "Oso de las cavernas †", nameEn: "Cave Bear †", cr: 2.0, crLabel: "2", ac: 12, hp: 42, hitDice: "5d10+15",
    speedWalk: 40, speedFly: 0, speedSwim: 30, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 20, dexterity: 10, constitution: 16,
    attacks: [{ name: "Mordisco", attackBonus: "+7", damage: "1d8+5 perforante (alcance 5 pies)" }, { name: "Garras", attackBonus: "+7", damage: "2d6+5 cortante (alcance 5 pies)" }],
    traits: "MA (Bite, Claws)", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: true, minDruidLevel: null, minMoonDruidLevel: 6, source: "MM p.334" },
  { id: "beast-polar-bear", name: "Oso polar", nameEn: "Polar Bear", cr: 2.0, crLabel: "2", ac: 12, hp: 42, hitDice: "5d10+15",
    speedWalk: 40, speedFly: 0, speedSwim: 30, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 20, dexterity: 10, constitution: 16,
    attacks: [{ name: "Mordisco", attackBonus: "+7", damage: "1d8+5 perforante (alcance 5 pies)" }, { name: "Garras", attackBonus: "+7", damage: "2d6+5 cortante (alcance 5 pies)" }],
    traits: "MA (Bite, Claws)", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: true, minDruidLevel: null, minMoonDruidLevel: 6, source: "MM p.334" },
  { id: "beast-plesiosaurus", name: "Plesiosaurio", nameEn: "Plesiosaurus", cr: 2.0, crLabel: "2", ac: 13, hp: 68, hitDice: "8d10+24",
    speedWalk: 20, speedFly: 0, speedSwim: 40, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 18, dexterity: 15, constitution: 16,
    attacks: [{ name: "Mordisco", attackBonus: "+6", damage: "3d6 + 4 perforante (alcance 10 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: null, minMoonDruidLevel: 6, source: "MM p.80" },
  { id: "beast-rhinoceros", name: "Rinoceronte", nameEn: "Rhinoceros", cr: 2.0, crLabel: "2", ac: 11, hp: 45, hitDice: "6d10+12",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 21, dexterity: 8, constitution: 15,
    attacks: [{ name: "Cornada", attackBonus: "+7", damage: "2d8+5 contundente (alcance 5 pies)" }],
    traits: "Charge", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: null, minMoonDruidLevel: 6, source: "MM p.336" },
  { id: "beast-giant-constrictor-snake", name: "Serpiente constrictora gigante", nameEn: "Giant Constrictor Snake", cr: 2.0, crLabel: "2", ac: 12, hp: 60, hitDice: "8d12+8",
    speedWalk: 30, speedFly: 0, speedSwim: 30, speedClimb: 0, speedBurrow: 0,
    size: "Enorme", strength: 19, dexterity: 14, constitution: 12,
    attacks: [{ name: "Mordisco", attackBonus: "+6", damage: "2d6 + 4 perforante (alcance 10 pies)" }, { name: "Constricción", attackBonus: "+6", damage: "2d8+4 contundente (alcance 5 pies) [NA, G/RS, DC 16]" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: null, minMoonDruidLevel: 6, source: "MM p.324" },
  { id: "beast-hunter-shark", name: "Tiburón cazador", nameEn: "Hunter Shark", cr: 2.0, crLabel: "2", ac: 12, hp: 45, hitDice: "6d10+12",
    speedWalk: 0, speedFly: 0, speedSwim: 40, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 18, dexterity: 13, constitution: 15,
    attacks: [{ name: "Mordisco", attackBonus: "+6", damage: "2d8+4 perforante (alcance 5 pies)" }],
    traits: "Blood Frenzy", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: null, minMoonDruidLevel: 6, source: "MM p.330" },
  { id: "beast-saber-toothed-tiger", name: "Tigre dientes de sable", nameEn: "Saber-Toothed Tiger", cr: 2.0, crLabel: "2", ac: 12, hp: 52, hitDice: "7d10+14",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 18, dexterity: 14, constitution: 15,
    attacks: [{ name: "Mordisco", attackBonus: "+6", damage: "1d10+5 perforante (alcance 5 pies)" }, { name: "Garras", attackBonus: "+6", damage: "2d6+5 cortante (alcance 5 pies)" }],
    traits: "Pounce", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: null, minMoonDruidLevel: 6, source: "MM p.336" },
  { id: "beast-ankylosaurus", name: "Anquilosaurio", nameEn: "Ankylosaurus", cr: 3.0, crLabel: "3", ac: 15, hp: 68, hitDice: "8d12+16",
    speedWalk: 30, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Enorme", strength: 19, dexterity: 11, constitution: 15,
    attacks: [{ name: "Cola", attackBonus: "+7", damage: "4d6 +4 contundente (alcance 10 pies) [DC 14 STR, PR, NA]" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: null, minMoonDruidLevel: 9, source: "MM p.79" },
  { id: "beast-giant-scorpion", name: "Escorpión gigante", nameEn: "Giant Scorpion", cr: 3.0, crLabel: "3", ac: 15, hp: 52, hitDice: "7d10+14",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 15, dexterity: 13, constitution: 15,
    attacks: [{ name: "Garra", attackBonus: "+4", damage: "1d8+2 contundente (alcance 5 pies) [NA, G, DC 12]" }, { name: "Aguijón", attackBonus: "+4", damage: "1d10+2 perforante (alcance 5 pies) [DC 12 CON, 4d10 PS | Half, NA]" }],
    traits: "MA (Two Claw, One Sting), Each Claw Can Grapple", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: true, minDruidLevel: null, minMoonDruidLevel: 9, source: "MM p.327" },
  { id: "beast-killer-whale", name: "Orca", nameEn: "Killer Whale", cr: 3.0, crLabel: "3", ac: 12, hp: 90, hitDice: "12d12+12",
    speedWalk: 0, speedFly: 0, speedSwim: 60, speedClimb: 0, speedBurrow: 0,
    size: "Enorme", strength: 19, dexterity: 10, constitution: 13,
    attacks: [{ name: "Mordisco", attackBonus: "+6", damage: "5d6+4 perforante (alcance 5 pies)" }],
    traits: "", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: null, minMoonDruidLevel: 9, source: "MM p.331" },
  { id: "beast-elephant", name: "Elefante", nameEn: "Elephant", cr: 4.0, crLabel: "4", ac: 12, hp: 76, hitDice: "8d12+24",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Enorme", strength: 22, dexterity: 9, constitution: 17,
    attacks: [{ name: "Cornada", attackBonus: "+8", damage: "3d8+6 perforante (alcance 5 pies)" }, { name: "Pisotón", attackBonus: "+8", damage: "M [PR], 3d10+6 contundente (alcance 5 pies)" }],
    traits: "Trampling Charge", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: null, minMoonDruidLevel: 12, source: "MM p.322" },
  { id: "beast-giant-crocodile", name: "Cocodrilo gigante", nameEn: "Giant Crocodile", cr: 5.0, crLabel: "5", ac: 14, hp: 85, hitDice: "9d12+27",
    speedWalk: 30, speedFly: 0, speedSwim: 50, speedClimb: 0, speedBurrow: 0,
    size: "Enorme", strength: 21, dexterity: 9, constitution: 17,
    attacks: [{ name: "Mordisco", attackBonus: "+8", damage: "3d10+5 perforante (alcance 5 pies) [NA, G/RS,DC 16]" }, { name: "Cola", attackBonus: "+8", damage: "2d8+5 contundente (alcance 10 pies) [DC 16 STR, PR, NA]" }],
    traits: "MA (Bite, Tail)", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: true, minDruidLevel: null, minMoonDruidLevel: 15, source: "MM p.324" },
  { id: "beast-water-elemental", name: "Elemental de agua", nameEn: "Water Elemental", cr: 5.0, crLabel: "5", ac: 14, hp: 114, hitDice: "12d10+48",
    speedWalk: 30, speedFly: 0, speedSwim: 90, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 18, dexterity: 14, constitution: 18,
    attacks: [{ name: "Golpe", attackBonus: "+7", damage: "2d8+4 contundente (alcance 5 pies)" }],
    traits: "MA (Two Slam), Whelm, Water Form, Freeze", vulnerabilities: null, resistances: "A, B, P, S", immunities: "PS", conditionImmunities: "E, G, PA, PE, PS, PR, RS, U",
    multiattack: true, minDruidLevel: null, minMoonDruidLevel: 10, source: "MM p.125" },
  { id: "beast-air-elemental", name: "Elemental de aire", nameEn: "Air Elemental", cr: 5.0, crLabel: "5", ac: 15, hp: 90, hitDice: "12d10+24",
    speedWalk: 0, speedFly: 90, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 14, dexterity: 20, constitution: 14,
    attacks: [{ name: "Golpe", attackBonus: "+8", damage: "2d8+5 contundente (alcance 5 pies)" }],
    traits: "MA (Two Slam), Whirlwind, Air Form", vulnerabilities: null, resistances: "L, T, B, P, S", immunities: "PS", conditionImmunities: "E, G, PA, PE, PS, PR, RS, U",
    multiattack: true, minDruidLevel: null, minMoonDruidLevel: 10, source: "MM p.124" },
  { id: "beast-fire-elemental", name: "Elemental de fuego", nameEn: "Fire Elemental", cr: 5.0, crLabel: "5", ac: 13, hp: 102, hitDice: "12d10+36",
    speedWalk: 50, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Grande", strength: 10, dexterity: 17, constitution: 16,
    attacks: [{ name: "Toque", attackBonus: "+6", damage: "2d6+3 fuego (alcance 5 pies)" }],
    traits: "MA (Two Touch), Fire Form, Illumination, Water Susceptibility", vulnerabilities: null, resistances: "B, P, S", immunities: "F, PS", conditionImmunities: "E, G, PA, PE, PS, PR, RS, U",
    multiattack: true, minDruidLevel: null, minMoonDruidLevel: 10, source: "MM p.125" },
  { id: "beast-earth-elemental", name: "Elemental de tierra", nameEn: "Earth Elemental", cr: 5.0, crLabel: "5", ac: 17, hp: 126, hitDice: "12d10+60",
    speedWalk: 30, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 30,
    size: "Grande", strength: 20, dexterity: 8, constitution: 20,
    attacks: [{ name: "Golpe", attackBonus: "+8", damage: "2d8+5 contundente (alcance 10 pies)" }],
    traits: "MA (Two Slam), Earth Glide, Siege Monster", vulnerabilities: "T", resistances: "B, P, S", immunities: "PS", conditionImmunities: "E, PA, PE, PS, U",
    multiattack: true, minDruidLevel: null, minMoonDruidLevel: 10, source: "MM p.124" },
  { id: "beast-giant-shark", name: "Tiburón gigante", nameEn: "Giant Shark", cr: 5.0, crLabel: "5", ac: 13, hp: 126, hitDice: "11d12+55",
    speedWalk: 0, speedFly: 0, speedSwim: 50, speedClimb: 0, speedBurrow: 0,
    size: "Enorme", strength: 23, dexterity: 11, constitution: 21,
    attacks: [{ name: "Mordisco", attackBonus: "+9", damage: "3d10+6 perforante (alcance 5 pies)" }],
    traits: "Blood Frenzy", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: null, minMoonDruidLevel: 15, source: "MM p.328" },
  { id: "beast-triceratops", name: "Triceratops", nameEn: "Triceratops", cr: 5.0, crLabel: "5", ac: 13, hp: 95, hitDice: "10d12+30",
    speedWalk: 50, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Enorme", strength: 22, dexterity: 9, constitution: 17,
    attacks: [{ name: "Cornada", attackBonus: "+9", damage: "4d8+6 perforante (alcance 5 pies)" }, { name: "Pisotón", attackBonus: "+9", damage: "M [PR], 3d10+6 contundente (alcance 5 pies)" }],
    traits: "Trampling Charge", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: null, minMoonDruidLevel: 15, source: "MM p.80" },
  { id: "beast-mammoth", name: "Mamut", nameEn: "Mammoth", cr: 6.0, crLabel: "6", ac: 13, hp: 126, hitDice: "11d12+55",
    speedWalk: 40, speedFly: 0, speedSwim: 0, speedClimb: 0, speedBurrow: 0,
    size: "Enorme", strength: 24, dexterity: 9, constitution: 21,
    attacks: [{ name: "Cornada", attackBonus: "+10", damage: "4d8+7 perforante (alcance 10 pies)" }, { name: "Pisotón", attackBonus: "+10", damage: "M [PR], 4d10+7 contundente (alcance 5 pies)" }],
    traits: "Trampling Charge", vulnerabilities: null, resistances: null, immunities: null, conditionImmunities: null,
    multiattack: false, minDruidLevel: null, minMoonDruidLevel: 18, source: "MM p.332" },
];

async function main() {
  console.log("Sembrando bestias de Forma Salvaje...");
  for (const beast of BEASTS) {
    await prisma.beastPreset.upsert({
      where: { id: beast.id },
      update: beast,
      create: beast,
    });
  }
  console.log(`${BEASTS.length} bestias sembradas.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });